In [170]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [171]:
cd /content/drive/MyDrive/ML_Medical

/content/drive/MyDrive/ML_Medical


In [172]:
import pandas as pd
import numpy as np
import graphviz
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [173]:
data_diabetes = pd.read_table('patients_data.txt',sep='\t',header=None)
classes_diabetes = pd.read_table('patients_classes.txt',sep='\t',header=None)

In [174]:
data_diabetes[1:5]

0          1  2  3
1  64.627752   7.970522  0  1
2  69.550752   6.368363  1  0
3  65.270695   8.812844  0  1
4  62.681176  10.322206  1  1

# **Decision tree**

In [175]:
clf_tree = tree.DecisionTreeClassifier()
clf_tree = clf_tree.fit(data_diabetes, classes_diabetes)

In [176]:
feature_names = ['age', 'hba1c', 'insuline taken', 'other drugs taken']
classes = ['DR','NDR']
dot_data = tree.export_graphviz(clf_tree, out_file=None,
                                             feature_names=feature_names,
                                             class_names=classes,
                                             filled=True,
                                             rounded=True,
                                             special_characters=True)

graph = graphviz.Source(dot_data)
graph.render("diabetes remission")

'diabetes remission.pdf'

In [177]:
clf_tree.predict(data_diabetes)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [178]:
clf_tree.feature_importances_

array([0.45163429, 0.29900847, 0.20852641, 0.04083083])

In [179]:
class_dia=(classes_diabetes.to_numpy()).reshape(1,-1)

In [180]:
class_dia

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]])

In [181]:
200-(clf_tree.predict(data_diabetes)==class_dia).sum()

0

We can see that the decision tree predict all the training set correctly.

# **Random forest**

In [182]:
clf_RF = RandomForestClassifier(max_depth=2, random_state=0)
clf_RF.fit(data_diabetes, classes_diabetes)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(max_depth=2, random_state=0)

In [183]:
clf_RF.predict(data_diabetes)

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1])

In [184]:
200-(clf_RF.predict(data_diabetes)==class_dia).sum()

36

But here, we observe that when we predict the training set with random forest, there are some error show up. We got 36 errors in total.

In [185]:
clf.feature_importances_

array([0.46472772, 0.12500739, 0.32924586, 0.08101903])

# **Diabetes Remission score**

In [186]:
def predict_Remission(data):
  score=np.zeros(len(data))
  pred=np.zeros(len(data))
  score[data[0]>=60]+=3
  score[(data[0]>=50)&(data[0]<60)]+=2
  score[(data[0]>=40)&(data[0]<50)]+=1

  score[(data[1]>=6.5)&(data[1]<9)]+=2
  score[(data[1]>=7)&(data[1]<9)]+=4
  score[data[1]>=9]+=6

  score[data[3]==1]+=3
  score[data[2]==1]+=10
  pred[score>=7]=1
  return (pred)


In [187]:
predict_Remission(data_diabetes)

array([1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1.,
       0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1.])

In [188]:
200-(predict_Remission(data_diabetes)==class_dia).sum()

63

By the state-of-the-art clinical score DiaRem model, we predict the training set with 63 errors for 200 data.

Among the 3 models we present above, it seems that the decision tree perform the best, with zero error in the prediction, but it is more likely because of overfitting, if we have a testing set with data do not trained in the models, we might get a different result.

# **With splitting the set**

Now, let's have a look of the performence of the models when we split the data set into a training set and a testing set, the training set contain 160 patients' data and the testing set contain 40 patients' data.

In [198]:
clf_tree_split = tree.DecisionTreeClassifier()
clf_tree_split = clf_tree.fit(data_diabetes[20:180], classes_diabetes[20:180])

In [199]:
40-(sum(clf_tree_split.predict(data_diabetes[0:20])==1)+sum(clf_tree.predict(data_diabetes[180:])==0))

14

In [191]:
clf_RF_split = RandomForestClassifier(max_depth=2, random_state=0)
clf_RF_split.fit(data_diabetes[20:180], classes_diabetes[20:180])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(max_depth=2, random_state=0)

In [192]:
40-(sum(clf_RF_split.predict(data_diabetes[0:20])==1)+sum(clf_RF_split.predict(data_diabetes[180:])==0))

14

In [193]:
40-(sum(predict_Remission(data_diabetes[0:20])==1)+sum(predict_Remission(data_diabetes[180:])==1))

8

We can see that we can not have a fully correct prediction with decision tree now, and the prediction error of random forest is near to the prediction decision tree model. Among them, the clinical score DiaRem model predict the best.